package com.example.util

import androidx.compose.runtime.Composable
import androidx.compose.runtime.compositionLocalOf
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.setValue

enum class AppLanguage(val code: String, val displayName: String, val shortName: String) {
    ENGLISH("en", "English", "EN"),
    HINDI("hi", "हिंदी", "HI")
}

object Strings {
    fun get(key: String, lang: AppLanguage): String {
        val enMap = mapOf(
            "app_title" to "Jan Sahayata",
            "app_subtitle" to "Direct Citizen Benefit & Assistance Scheme Portal",
            "tagline" to "Empowering Citizens, Enabling Direct Benefits",
            "home" to "Home",
            "login" to "Citizen Login",
            "register" to "Register",
            "admin_login" to "Officer / Admin Login",
            "dashboard" to "Dashboard",
            "my_applications" to "My Applications",
            "new_application" to "New Application",
            "draft_applications" to "Drafts",
            "submitted_applications" to "Submitted",
            "application_status" to "Track Status",
            "profile" to "Citizen Profile",
            "logout" to "Logout",
            "switch_lang" to "हिंदी",
            "current_lang" to "English",

            // Home sections
            "portal_badge" to "Citizen Welfare Initiative",
            "hero_heading" to "Direct Benefit Transfer & Girl Child Scheme",
            "hero_description" to "Apply easily online for state social welfare, educational incentives, and direct DBT assistance. Transparent, secure, and trackable end-to-end.",
            "hero_apply_btn" to "Apply for Scheme",
            "hero_track_btn" to "Track Application",
            "services_heading" to "Key Scheme Services",
            "service_1_title" to "Girl Child Welfare Grant",
            "service_1_desc" to "Direct financial assistance at birth, primary school admission, and higher secondary milestones.",
            "service_2_title" to "Education & Scholarship DBT",
            "service_2_desc" to "Direct-to-bank account incentive for textbooks, uniform, and girl-child education continuity.",
            "service_3_title" to "Family Economic Support",
            "service_3_desc" to "Special annual grants for eligible families registered under Jan Sahayata portal.",
            "eligibility_heading" to "Eligibility Criteria",
            "eligibility_point_1" to "Permanent resident of the state with valid residential certificate/proof.",
            "eligibility_point_2" to "Annual family income less than ₹2,50,000 from all sources.",
            "eligibility_point_3" to "Maximum of two living children per household eligible for the scheme.",
            "eligibility_point_4" to "Beneficiary must have a registered birth certificate issued by competent authority.",
            "eligibility_point_5" to "Active Aadhaar-linked savings bank account in beneficiary or mother's name.",
            "docs_heading" to "Mandatory Documents Required",
            "doc_1" to "Aadhaar Card (Only last 4 digits verified)",
            "doc_2" to "Birth Certificate of Beneficiary Child",
            "doc_3" to "Proof of Residence (Electricity/Ration Card/Domicile)",
            "doc_4" to "Bank Passbook or Cancelled Cheque (with IFSC)",
            "doc_5" to "Passport Size Photograph of Child/Applicant",
            "doc_6" to "Self-declaration of family income & category",
            "how_it_works_heading" to "How the Scheme Works",
            "step_1_title" to "1. Online Registration",
            "step_1_desc" to "Create your verified citizen account using mobile number and Aadhaar last 4 digits.",
            "step_2_title" to "2. Fill Application",
            "step_2_desc" to "Complete the 7-step wizard with applicant, beneficiary, bank details, and documents.",
            "step_3_title" to "3. Scrutiny & Verification",
            "step_3_desc" to "Designated block & district welfare officers verify eligibility and documents.",
            "step_4_title" to "4. Direct Benefit Disbursement",
            "step_4_desc" to "Sanctioned amount credited directly to bank account via DBT PFMS gateway.",
            "faq_heading" to "Frequently Asked Questions (FAQ)",
            "faq_q1" to "Is there any application fee for Jan Sahayata scheme?",
            "faq_a1" to "No. The Jan Sahayata application and verification process is 100% free of cost.",
            "faq_q2" to "Can I edit my application after submission?",
            "faq_a2" to "You can edit your application while it is in 'Draft' status or when an officer has 'Returned for Correction'. Once under final review or approved, it is locked.",
            "faq_q3" to "How long does verification take?",
            "faq_a3" to "Usually 7 to 15 working days from submission of complete documents.",
            "faq_q4" to "What if my bank account is not Aadhaar-seeded?",
            "faq_a4" to "Please visit your bank branch to seed Aadhaar with your bank account so DBT transfers succeed.",
            "help_heading" to "Citizen Helpdesk & Grievance",
            "helpline" to "Toll-Free Helpline: 1800-233-5267 (Mon-Sat, 9:30 AM to 6:00 PM)",
            "email_support" to "Email: helpdesk@jansahayata.gov.in",
            "disclaimer_title" to "Public Information Disclaimer",
            "disclaimer_text" to "Jan Sahayata is an independent citizen facilitation platform. This system implements preliminary eligibility checks; the final decision rests solely with the competent sanctioning authority. Please safeguard your login credentials and never share OTPs with anyone.",

            // Auth
            "full_name" to "Full Name (as in Aadhaar)",
            "mobile_number" to "Mobile Number",
            "email_address" to "Email Address",
            "password" to "Password",
            "confirm_password" to "Confirm Password",
            "state" to "State",
            "district" to "District",
            "address" to "Complete Residential Address",
            "aadhaar_last4" to "Aadhaar Number (Last 4 digits only)",
            "aadhaar_hint" to "Enter last 4 digits (e.g. 5892)",
            "consent_label" to "I hereby declare that all information provided is true and I authorize Jan Sahayata to verify my details for scheme benefits.",
            "otp_title" to "Verify Mobile OTP",
            "otp_desc" to "A 6-digit verification code has been sent to your mobile",
            "enter_otp" to "Enter 6-Digit OTP",
            "verify_proceed" to "Verify OTP & Complete Registration",
            "resend_otp" to "Resend OTP",
            "already_registered" to "Already have an account? Login here",
            "new_user" to "New Citizen? Register here",
            "login_btn" to "Secure Login",
            "forgot_pwd" to "Forgot Password?",
            "login_as_admin" to "Portal Administration Login",
            "admin_badge" to "Administrative Portal",

            // Status
            "status_draft" to "Draft",
            "status_submitted" to "Submitted",
            "status_under_review" to "Under Review",
            "status_document_verification" to "Document Verification",
            "status_approved" to "Approved",
            "status_rejected" to "Rejected",
            "status_returned_for_correction" to "Returned for Correction",

            // Wizard steps
            "step_applicant" to "Applicant Details",
            "step_beneficiary" to "Beneficiary Details",
            "step_bank" to "Bank Details",
            "step_eligibility" to "Eligibility Check",
            "step_documents" to "Upload Documents",
            "step_review" to "Review & Declaration",
            "step_submit" to "Submit & Acknowledgement"
        )

        val hiMap = mapOf(
            "app_title" to "जन सहायता",
            "app_subtitle" to "नागरिक प्रत्यक्ष लाभ एवं सहायता योजना पोर्टल",
            "tagline" to "नागरिकों का सशक्तिकरण, सीधा लाभ हस्तांतरण",
            "home" to "मुख्य पृष्ठ",
            "login" to "नागरिक लॉगिन",
            "register" to "नया पंजीकरण",
            "admin_login" to "अधिकारी / एडमिन लॉगिन",
            "dashboard" to "डैशबोर्ड",
            "my_applications" to "मेरे आवेदन",
            "new_application" to "नया आवेदन",
            "draft_applications" to "प्रारूप (ड्राफ्ट)",
            "submitted_applications" to "जमा किए गए आवेदन",
            "application_status" to "स्थिति जांचें",
            "profile" to "नागरिक प्रोफाइल",
            "logout" to "लॉगआउट",
            "switch_lang" to "English",
            "current_lang" to "हिंदी",

            // Home sections
            "portal_badge" to "नागरिक कल्याण सेवा",
            "hero_heading" to "प्रत्यक्ष लाभ अंतरण (DBT) एवं कन्या सहायता योजना",
            "hero_description" to "राज्य कल्याणकारी योजनाओं, शिक्षा प्रोत्साहन एवं कन्या सहायता के लिए सरलता से ऑनलाइन आवेदन करें। पारदर्शी, सुरक्षित एवं ट्रैक करने योग्य।",
            "hero_apply_btn" to "योजना हेतु आवेदन करें",
            "hero_track_btn" to "आवेदन की स्थिति जांचें",
            "services_heading" to "मुख्य योजना सेवाएं",
            "service_1_title" to "कन्या कल्याण सहायता अनुदान",
            "service_1_desc" to "जन्म, प्राथमिक विद्यालय प्रवेश तथा उच्चतर माध्यमिक स्तर पर चरणबद्ध प्रत्यक्ष आर्थिक सहायता।",
            "service_2_title" to "शिक्षा एवं छात्रवृत्ति DBT",
            "service_2_desc" to "पुस्तकों, वर्दी और बालिका शिक्षा निरंतरता हेतु सीधे बैंक खाते में आर्थिक सहायता।",
            "service_3_title" to "पारिवारिक संबल योजना",
            "service_3_desc" to "जन सहायता पोर्टल के तहत पंजीकृत पात्र परिवारों के लिए विशेष वार्षिक संबल अनुदान।",
            "eligibility_heading" to "पात्रता मापदंड",
            "eligibility_point_1" to "संबंधित राज्य का मूल/स्थायी निवासी होना अनिवार्य है।",
            "eligibility_point_2" to "परिवार की कुल वार्षिक आय ₹2,50,000 से कम होनी चाहिए।",
            "eligibility_point_3" to "प्रति परिवार अधिकतम दो जीवित बालिकाओं/बच्चों हेतु योजना अनुमन्य है।",
            "eligibility_point_4" to "सक्षम प्राधिकारी द्वारा जारी वैध जन्म प्रमाण पत्र होना अनिवार्य है।",
            "eligibility_point_5" to "लाभार्थी या माता के नाम से आधार से जुड़ा सक्रिय बचत बैंक खाता होना आवश्यक है।",
            "docs_heading" to "आवश्यक महत्वपूर्ण दस्तावेज",
            "doc_1" to "आधार कार्ड (केवल अंतिम 4 अंक सत्यापित)",
            "doc_2" to "बालिका/लाभार्थी का जन्म प्रमाण पत्र",
            "doc_3" to "निवास प्रमाण पत्र (बिजली बिल / राशन कार्ड / निवास)",
            "doc_4" to "बैंक पासबुक या निरस्त चेक (IFSC कोड सहित)",
            "doc_5" to "बालिका/आवेदक का पासपोर्ट आकार का फोटो",
            "doc_6" to "परिवार आय एवं श्रेणी स्व-घोषणा पत्र",
            "how_it_works_heading" to "योजना की कार्यप्रणाली",
            "step_1_title" to "1. ऑनलाइन पंजीकरण",
            "step_1_desc" to "मोबाइल नंबर और आधार के अंतिम 4 अंकों के साथ सत्यापित नागरिक खाता बनाएं।",
            "step_2_title" to "2. आवेदन भरें",
            "step_2_desc" to "आवेदक, लाभार्थी, बैंक विवरण एवं दस्तावेज 7 चरणों में सरलता से दर्ज करें।",
            "step_3_title" to "3. जांच एवं सत्यापन",
            "step_3_desc" to "नामित प्रखंड व जिला कल्याण अधिकारियों द्वारा दस्तावेजों की गहन जांच।",
            "step_4_title" to "4. बैंक खाते में सीधा लाभ",
            "step_4_desc" to "स्वीकृत राशि सीधे PFMS / DBT द्वारा बैंक खाते में जमा की जाती है।",
            "faq_heading" to "अक्सर पूछे जाने वाले प्रश्न (FAQ)",
            "faq_q1" to "क्या जन सहायता योजना का कोई आवेदन शुल्क है?",
            "faq_a1" to "नहीं। जन सहायता पर आवेदन व सत्यापन पूर्णतः निःशुल्क है।",
            "faq_q2" to "क्या आवेदन जमा करने के बाद सुधार किया जा सकता है?",
            "faq_a2" to "आवेदन ड्राफ्ट अवस्था में या अधिकारी द्वारा 'सुधार हेतु वापस' भेजे जाने पर ही संशोधित किया जा सकता है।",
            "faq_q3" to "सत्यापन प्रक्रिया में कितना समय लगता है?",
            "faq_a3" to "सभी दस्तावेज सही पाए जाने पर सामान्यतः 7 से 15 कार्य दिवस।",
            "faq_q4" to "यदि बैंक खाता आधार से लिंक नहीं है तो क्या करें?",
            "faq_a4" to "कृपया अपनी बैंक शाखा में जाकर आधार सीडिंग करवाएं ताकि DBT राशि जमा हो सके।",
            "help_heading" to "नागरिक सहायता एवं शिकायत निवारण",
            "helpline" to "टोल-फ्री हेल्पलाइन: 1800-233-5267 (सोम-शनि, सुबह 9:30 से शाम 6:00 तक)",
            "email_support" to "ईमेल: helpdesk@jansahayata.gov.in",
            "disclaimer_title" to "सार्वजनिक सूचना एवं अस्वीकरण",
            "disclaimer_text" to "जन सहायता एक स्वतंत्र नागरिक सुविधा मंच है। यह प्रणाली प्रारंभिक पात्रता जांच करती है; अंतिम स्वीकृति का अधिकार सक्षम प्रशासनिक प्राधिकारी के पास सुरक्षित है। अपना पासवर्ड और OTP किसी के साथ साझा न करें।",

            // Auth
            "full_name" to "पूरा नाम (आधार अनुसार)",
            "mobile_number" to "मोबाइल नंबर",
            "email_address" to "ईमेल आईडी",
            "password" to "पासवर्ड",
            "confirm_password" to "पासवर्ड की पुष्टि करें",
            "state" to "राज्य",
            "district" to "जिला",
            "address" to "पूरा स्थायी निवास पता",
            "aadhaar_last4" to "आधार संख्या (केवल अंतिम 4 अंक)",
            "aadhaar_hint" to "अंतिम 4 अंक दर्ज करें (उदा. 5892)",
            "consent_label" to "मैं प्रमाणित करता/करती हूँ कि दी गई जानकारी सत्य है और मैं जन सहायता को सत्यापन की सहमति देता/देती हूँ।",
            "otp_title" to "मोबाइल OTP सत्यापन",
            "otp_desc" to "आपके पंजीकृत मोबाइल पर 6 अंकों का OTP भेजा गया है",
            "enter_otp" to "6 अंकों का OTP दर्ज करें",
            "verify_proceed" to "सत्यापित करें और पंजीकरण पूरा करें",
            "resend_otp" to "OTP पुनः भेजें",
            "already_registered" to "पहले से खाता है? यहाँ लॉगिन करें",
            "new_user" to "नया नागरिक? यहाँ पंजीकरण करें",
            "login_btn" to "सुरक्षित लॉगिन",
            "forgot_pwd" to "पासवर्ड भूल गए?",
            "login_as_admin" to "अधिकारी एवं एडमिन लॉगिन",
            "admin_badge" to "प्रशासनिक पोर्टल",

            // Status
            "status_draft" to "प्रारूप (ड्राफ्ट)",
            "status_submitted" to "जमा किया गया",
            "status_under_review" to "समीक्षाधीन",
            "status_document_verification" to "दस्तावेज सत्यापन",
            "status_approved" to "स्वीकृत",
            "status_rejected" to "अस्वीकृत",
            "status_returned_for_correction" to "सुधार हेतु वापस",

            // Wizard steps
            "step_applicant" to "आवेदक विवरण",
            "step_beneficiary" to "लाभार्थी विवरण",
            "step_bank" to "बैंक विवरण",
            "step_eligibility" to "पात्रता जांच",
            "step_documents" to "दस्तावेज अपलोड",
            "step_review" to "समीक्षा एवं घोषणा",
            "step_submit" to "जमा एवं पावती"
        )

        val map = if (lang == AppLanguage.HINDI) hiMap else enMap
        return map[key] ?: enMap[key] ?: key
    }
}
